<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Book now' => 'Забронировать',
    'Booked' => 'Забронировано',
    'Cabinet' => 'Личный кабинет',
    'Captcha' => 'Введите проверочный код',
    'Create' => 'Создать',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Information saved successfully' => 'Информация успешно сохранена',
    'Information not saved' => 'Информация не сохранена',
    'My cars' => 'Мои автомобили',
    'Not valid' => 'Не валидный',
    'Phone' => 'Телефон',
    'Reset' => 'Сбросить',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Update' => 'Обновить',
    'Upload' => 'Загрузить',
    'Upload excel' => 'Загрузить excel',
    'Username' => 'Имя пользователя',


    'January' => 'Январь',
    'February' => 'Февраль',
    'March' => 'Март',
    'April' => 'Апрель',
    'May' => 'Май',
    'June' => 'Июнь',
    'July' => 'Июль',
    'August' => 'Август',
    'September' => 'Сентябрь',
    'October' => 'Октябрь',
    'November' => 'Ноябрь',
    'December' => 'Декабрь',
];

